# docker-compose.yml
services:
  whisper-api:
    build: .
    ports:
      - "9673:9673"
    volumes:
      - ./uploads:/app/uploads
    user: "${UID}:${GID}"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    shm_size: '8gb'  # Increased shared memory
    ulimits:
      memlock: -1
      stack: 67108864
    restart: unless-stopped  # Ensures service keeps running
    command: >
      uvicorn main:app
      --host 0.0.0.0
      --port 9673
      --timeout-keep-alive 300
      --workers 1
      --log-level info
      --reload
      --reload-dir /app